Shortening of long lists with a x remaining message and popup#90
ebi-ait/data-catalogue-frontend pull request #3
Opened 2024-02-21 12:18 UTC by theisuru

ebi-ait/data-catalogue#90

Whats in this pull request
- React class component to render more list values in a cell
- Render all array type values in the gird using this component

Points to discuss
- Naming is not very good any suggested name for this component?
- Currently this will render any array value in the schema, becaues of the way ag grid is defined from `schema`. This needs to be discussed. 
- UI and design

2024-02-21 18:01 UTC, sandsebi commented
Looks good to me. Maybe we should set up [Github codespaces](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-github-codespaces#monthly-included-storage-and-core-hours-for-personal-accounts) so we can see an actual live version of each PR, it works similar to CodeSandBox. But seems to be free for 120 hours per month.

2024-02-27 16:16 UTC, amnonkhen requested changes

2024-02-27 16:16 UTC, amnonkhen commented on src/theme/theme.css
>  }
👍

2024-02-27 16:16 UTC, amnonkhen commented on src/MoreCellRenderer/MoreCellRenderer.module.css
> +.MoreCellWrapper {
class names usually start with a lowercase letter

2024-02-27 16:25 UTC, amnonkhen requested changes

2024-02-27 16:25 UTC, amnonkhen commented on src/MoreCellRenderer/MoreCellRenderer.tsx
> +                    </Popover></div>}
```suggestion
                    </Popover>
                </div>}
```

2024-03-01 09:35 UTC, theisuru commented on src/Catalogue.tsx
>                          return params.newValue.split(',');
actually we don't need this code segment. I will remove it.

2024-03-01 09:40 UTC, theisuru commented on src/MoreCellRenderer/MoreCellRenderer.tsx
> +export default class MoreCellRenderer extends React.Component<{ value: string[] }, MoreCellRendererState> {
This is not a plural value. It is the div element that is holding the popover

2024-03-01 09:47 UTC, theisuru commented
Renamed to `ListCellRenderer". I think it would make sense to have all `cell renderer` with a same naming convention and inside a one directory, later when we have more cell renderer types.

2024-03-04 14:37 UTC, amnonkhen approved these changes

2024-03-04 14:53 UTC, merged