initial commit side filters
ebi-ait/data-catalogue-frontend pull request #9
Opened 2024-02-28 11:04 UTC by snathanvj

2024-02-28 12:44 UTC, amnonkhen requested changes

2024-02-28 12:44 UTC, amnonkhen commented on package.json
> +    "@mui/x-data-grid": "latest",
This needs to be deleted, as we are not using mui's data-grid.

2024-02-28 12:44 UTC, amnonkhen commented on src/SideFilter.jsx
> +            <List>
I beieve we should use [the auto-complete](https://mui.com/material-ui/react-autocomplete) control here. Start simple, only allowing a single selection, and we'll work our way up.

2024-02-28 12:45 UTC, amnonkhen commented
please make sure to connect the pr to the ticket. It makes review easier and quicker.

2024-03-01 10:05 UTC, theisuru commented on src/SideFilter.jsx
We should use `TypeScript` instead of `JavaScript`

2024-03-01 10:09 UTC, theisuru commented on src/SideFilter.jsx
Check the [multi select section](https://mui.com/material-ui/react-select/). Use `TS` box to see TypeScript code.

2024-03-08 10:39 UTC, merged